### PR TITLE
add a `Procfile.example`, plus corresponding explanation in `README.md`

### PR DESCRIPTION
**Pull request by bchase**
First off, thanks so much for this buildpack! I'm just getting started with Haskell, and was thrilled to find I could use Stack + Heroku this easily. Seriously, thank you!

After my first deploy, I missed the helpful message about `app/.local/bin`, and ended up pointing my `Procfile` to the binary in `.stack-work`, before noticing it contained version numbers, and deciding that was an absolutely terrible idea. I eventually found the message, but figured adding a `Procfile.example` and some notes to `Usage` might save the next newbie a few minutes time!

### CODE REVIEW

**Comment by mfine** [comment]
`/app/.local/bin` should be on your path - you shouldn't need to use absolute or relative paths to your binaries:

```
➜ heroku run bash
Running bash on ⬢ secret-refuge-28623... up, run.2979 (Free)
~ $ echo $PATH
/app/.local/bin:/app/.local/bin:/app/vendor/bin:/usr/local/bin:/usr/bin:/bin:/tmp/codon/vendor/bin
~ $
~ $ which simple
/app/.local/bin/simple
~ $ 
```

Is that not the case for you?

**Comment by bchase** [comment]
Oh, better yet! Thanks!

I hadn't consider to check that for some reason... I guess since I've mostly kicked things off on Heroku with `bundle exec` in Ruby and `mix` in Elixir, rather than pointing at my own binary.

Hmm. Do you think that'd be worth mentioning that in the README then? i.e. that the binaries get placed in `/app/.local/bin` and that's included in `$PATH`. ... At this point, I'm tempted to say that it's so obvious it's hardly worth mentioning, except that I clearly missed it. :smile:

If not, feel free to just close this. I can adjust the README if you think it's warranted though. Either way, thanks for pointing that out!

**Comment by mfine** [comment]
Sure, that'd be great, thanks!

**Comment by turboMaCk** [comment]
@bchase THX this saved me!

**Comment by bchase** [comment]
@mfine All right, how's it look now? :smile:

**Pull request merged**
